import core.calibration as calibration
import click
from pathlib import Path

@click.group()
def cli():
    pass

@cli.command(
    help = "Generates a calibration curve (pressure v. intensity) based on a set of .cine files of known pressure values."
)
@click.option(
    "--data-dir",
    "data_dir_path",
    type = click.Path(exists=True, file_okay=False, dir_okay=True, path_type=Path, readable=True, resolve_path=True),
    help = "Folder containing .cine files at varying pressures.",
    required=True,
)
@click.option(
    "--output",
    "output_file_path",
    type=click.Path(exists=False, file_okay=True, dir_okay=False, path_type=Path, writable=True, resolve_path=True),
    help = "File to output the calibration coefficients to. Will be overwritten.",
    default = "calibration.poly"
)
@click.option(
    "--atmospheric-pressure",
    "atmospheric_pressure",
    type = click.FloatRange(500, 2000),
    help = "The atmospheric pressure value in hPa",
    default = 1013.25,
)
def generate_calibration(data_dir_path: Path, output_file_path: Path, atmospheric_pressure: float):
    captures = calibration.ExperimentalCapture.from_folder(data_dir_path)
    cropped_captures = calibration.prompt_crop_captures(captures)

    pressure_intensity_map = calibration.create_pressure_intensity_map(cropped_captures)
    calibration_curve = calibration.plot_pressure_v_intensity(pressure_intensity_map, atmospheric_pressure).convert()

    with open(output_file_path, "w") as output_file:
        output_file.write(f"{calibration_curve.coef[0]},{calibration_curve.coef[1]},{atmospheric_pressure}")

@cli.command(
    help = "Compares one capture to a wind-off capture, given a calibration file."
)
@click.option(
    "--wind-off",
    "wind_off_path",
    type = click.Path(exists=True, file_okay=True, dir_okay=False, path_type=Path, readable=True, resolve_path=True),
    help = ".cine file containing the wind-off capture.",
    required=True,
)
@click.option(
    "--calibration",
    "calibration_file_path",
    type = click.Path(exists=True, file_okay=True, dir_okay=False, path_type=Path, readable=True, resolve_path=True),
    help = "The calibration file generated by generate-calibration",
    default = "calibration.poly",
)
@click.option(
    "--wind-on",
    "wind_on_path",
    type = click.Path(exists=True, file_okay=True, dir_okay=False, path_type=Path, readable=True, resolve_path=True),
    help = ".cine file containing the wind-on capture.",
    required=True,
)
def process_capture(wind_off_path: Path, wind_on_path: Path, calibration_file_path: Path):
    A, B, P_ref = None,None,None

    with open(calibration_file_path, "r") as calibration_file:
        A, B, P_ref = [float(x) for x in calibration_file.read().split(",")]

    

if __name__ == "__main__":
    cli()