import click
import cv2
import numpy as np
from pathlib import Path
from cli.group import cli
from core import process,capture

def nothing(x):
    pass

@cli.command(
    help = "Compares one capture to a wind-off capture, given a calibration file."
)
@click.option(
    "--wind-off",
    "wind_off_path",
    type = click.Path(exists=True, file_okay=True, dir_okay=False, path_type=Path, readable=True, resolve_path=True),
    help = ".cine file containing the wind-off capture.",
    required=True,
)
@click.option(
    "--calibration",
    "calibration_file_path",
    type = click.Path(exists=True, file_okay=True, dir_okay=False, path_type=Path, readable=True, resolve_path=True),
    help = "The calibration file generated by generate-calibration",
    default = "calibration.poly",
)
@click.option(
    "--wind-on",
    "wind_on_path",
    type = click.Path(exists=True, file_okay=True, dir_okay=False, path_type=Path, readable=True, resolve_path=True),
    help = ".cine file containing the wind-on capture.",
    required=True,
)
def process_capture(wind_off_path: Path, wind_on_path: Path, calibration_file_path: Path):
    A, B, P_ref = None,None,None

    with open(calibration_file_path, "r") as calibration_file:
        A, B, P_ref = [float(x) for x in calibration_file.read().split(",")]

    wind_off_frame = capture.ExperimentalCapture.from_cine(wind_off_path).post_process()
    wind_on_frame = capture.ExperimentalCapture.from_cine(wind_on_path).post_process() # TODO: align wind on with wind off
    ratio_map = process.compute_ratio(wind_off_frame, wind_on_frame)
    pressure_map = process.ratio_to_pressure(ratio_map, A, B, P_ref)

    title = f"Pressure map ({wind_on_path.stem} v. {wind_off_path.stem})"
    cv2.namedWindow(title)
    cv2.createTrackbar("P_min", title, 0, round(pressure_map.max() - pressure_map.min()), nothing)
    cv2.createTrackbar("P_max", title, 0, round(pressure_map.max() - pressure_map.min()), nothing)
    cv2.setTrackbarPos("P_max", title, round(pressure_map.max() - pressure_map.min()))

    cursor_pressure: float = 0
    def mouse_callback(event, x, y, flags, params):
        nonlocal cursor_pressure

        if event == cv2.EVENT_MOUSEMOVE:
            cursor_pressure = pressure_map[y][x] # type: ignore
    cv2.setMouseCallback(title, mouse_callback)

    while True:
        min_val: float = cv2.getTrackbarPos("P_min", title)
        max_val: float = cv2.getTrackbarPos("P_max", title)
        
        if min_val > max_val:
            cv2.setTrackbarPos("P_min", title, max_val)
            min_val = max_val

        min_val -= abs(pressure_map.min())
        max_val -= abs(pressure_map.min())

        normalized_pressure_map = process.normalize_map(pressure_map, min_val, max_val)
        colorized_pressure_map = cv2.applyColorMap(normalized_pressure_map, cv2.COLORMAP_JET)

        cv2.putText(colorized_pressure_map, f"P at cursor: {cursor_pressure:.3f} Pa", (0, 25), cv2.FONT_HERSHEY_SIMPLEX, 0.75, (0, 0, 0), 2)
        cv2.imshow(title, colorized_pressure_map)
    
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    cv2.destroyAllWindows()
    